application: lp-demo
version: 3
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /img
  static_dir: static/img
- url: /files
  static_dir: static/files
- url: .*
  script: main.py
